wrap_comments = true
reorder_imports = true
trailing_semicolon = false
use_field_init_shorthand = true
format_code_in_doc_comments = true

binop_separator = "Back"
trailing_comma = "Vertical"
use_small_heuristics = "Max"
imports_granularity = "Crate"

comment_width = 100
doc_comment_code_block_width = 100